### ISSUE TITLE
Unknown Method – yii\base\UnknownMethodException Calling unknown method: kartik\datetime\DateTimePicker::isBs4()

### ISSUE THREAD

**Issue by pandora-iuz** [kartik-v/yii2-widget-datetimepicker#101]
![image](https://user-images.githubusercontent.com/11518967/56705717-ba25fe80-6744-11e9-92d4-10fde06165b7.png)

**Comment by buttflattery** [comment]
@pandora-iuz  you might not have installed [krajee-base](https://github.com/kartik-v/yii2-krajee-base) which includes the `BootstrapTrait.php` that has this method defined.

**Comment by kartik-v** [comment]
Yes - update your extension via composer to get all dependencies from other extensions. This happens if you are manually copying just this extension.
