### ISSUE TITLE
Problems with unix timestamp and convertion

### ISSUE THREAD

**Issue by prsolucoes** [kartik-v/yii2-widget-datetimepicker#106]
Hi,

Im using latest version of library and im search a lot for this but don't find anything that solve my problem.

1. My domain class Banner has two fields: "start_at" and "end_at";
2. Both fields are integer to store timestamp;

Problems:

1. When i show the field value it shows as timestamp and not "d/m/Y H:i:s":
![image](https://user-images.githubusercontent.com/395096/72302663-95164a80-3649-11ea-952f-0133669a35c5.png)

2. Validation of integer number fails because validation consider the date string and not the date as timestamp:

![image](https://user-images.githubusercontent.com/395096/72303081-df4bfb80-364a-11ea-8ef0-914354659cf4.png)

Can you help me use it correctly? I tried put the configurations on module, but no effect:

```
'modules' => [
        'datecontrol' => [
            'class' => '\kartik\datecontrol\Module',
            'saveTimezone' => 'UTC',
            'saveSettings' => [
                Module::FORMAT_DATETIME => 'php:U',
            ],
            'ajaxConversion' => true,
            'autoWidget' => true,
        ]
],
```

I tried put on field, but don't work:

```
<?php echo $form->field($model, 'start_at')->widget(DateTimePicker::class, [
    'options' => [
        'type' => DateControl::FORMAT_DATETIME,
        'format' => 'datetime',
    ],
    'convertFormat' => true,
    'pluginOptions' => [
        'autoclose' => true,
        'todayHighlight' => true,
        'todayBtn' => true,
        'format' => 'php:d/m/Y H:i:s',
    ]
]); ?>
```

Thanks for any help.

**Comment by buttflattery** [comment]
you are using `convertFormat=>true` so `'format' => 'd/m/Y H:i:s',` should work fine @prsolucoes and `format` option is the javascript plugin's option so it should be under `pluginOptions` option

**Comment by prsolucoes** [comment]
Hi,

I changed to:

```
<?php echo $form->field($model, 'start_at')->widget(DateTimePicker::class, [
    'options' => [
        'type' => DateControl::FORMAT_DATETIME,
    ],
    'convertFormat' => true,
    'pluginOptions' => [
        'autoclose' => true,
        'todayHighlight' => true,
        'todayBtn' => true,
        'format' => 'php:d/m/Y H:i:s',
    ]
]); ?>
```

But the validation don't work. It show that the string date is not integer. Validation don't consider the field as timestamp.
