### ISSUE TITLE
InlineOptions mentioned but not implemented

### ISSUE THREAD

**Issue by XzAeRo** [kartik-v/yii2-widget-datetimepicker#109]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-datetimepicker.
- [x] This is not an usage question. I confirm having gone through and read the documentation for [datetimepicker](http://demos.krajee.com/widget-details/datetimepicker) and [ActiveField](http://demos.krajee.com/widget-details/active-field).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Create a widget with `type` set to `DateTimePicker::TYPE_INLINE`, and try to override the `readonly` parameter.

```php
<?= $form->field($model, 'start_date')->widget(DateTimePicker::class, [
    'type' => DateTimePicker::TYPE_INLINE,
    'readonly' => false, // ignored due to type
    'inlineOptions' => [
        'readonly' => false,  // throws error
    ],
    'pluginOptions' => [
        'format' => 'yyyy-mm-dd hh:ii:ss',
        'inlineOptions' => [
            'readonly' => false, // completely ignored
        ],
    ],
]) ?>
```

## Expected behavior and actual behavior

When I follow those steps, I see `Setting unknown property: kartik\datetime\DateTimePicker::inlineOptions` error.

I was expecting to override some property values according to the documentation:
![Screenshot_2021-01-13 Date Time Picker - © Kartik](https://user-images.githubusercontent.com/1656037/104407577-a6d24c80-5540-11eb-9254-0f5cb84543ad.png)

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 3.5.1 (latest stable)
- yii2-widget-datetimepicker version: 1.4.9 (latest tag)

## Isolating the problem

- [x] This bug happens [on the demos page](http://demos.krajee.com/widget-details/datetimepicker) (supposedly)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-widget-datetimepicker without other plugins.

**Comment by buttflattery** [comment]
@kartik-v i think you wanted to say `inputOptions` rather than the `inlineOptions` in the documentation where @XzAeRo is pointing, secondly it wont work just mentioning the `'readonly'=>false` under the `inputOptions` , because you are checking for the `empty($this->options['readonly'])`  in the `renderInput` which will always make it readonly either you pass true or false 

```
<?= $form->field($model, 'start_date',['inputOptions'=>['readonly'=>false]])->widget(DateTimePicker::class, [
    'type' => DateTimePicker::TYPE_INLINE,
    'readonly' => false, // ignored due to type
    'inlineOptions' => [
        'readonly' => false,  // throws error
    ],
    'pluginOptions' => [
        'format' => 'yyyy-mm-dd hh:ii:ss',
        'inlineOptions' => [
            'readonly' => false, // completely ignored
        ],
    ],
]) ?>
```

changing it to `if (!isset($this->options['readonly'])) {` will work correctly
