### ISSUE TITLE
isBs function does not exist

### ISSUE THREAD

**Issue by SattarovAR** [kartik-v/yii2-widget-datetimepicker#111]
https://github.com/kartik-v/yii2-widget-datetimepicker/blob/881985a5e482a4e37d1901c7857912ba5af3f298/src/DateTimePicker.php#L166

**Comment by kartik-v** [comment]
You need to update packages via composer to install the necessary dependencies (this is happening for you because you may have manually updated this extension - you need to ensure you have latest release of the dependencies - in this case yii2-krajee-base).

**Comment by Henning-IG** [comment]
I had trouble with this, too.
I think there is an issue with dependecies. isBs() is new in yii2-krajee-base 3.0.0. But latest yii2-widget-datetimepicker just requires "kartik-v/yii2-krajee-base": ">=2.0.0" in composer.json
