### ISSUE TITLE
Calling unknown method: kartik\datetime\DateTimePicker::isBs()

### ISSUE THREAD

**Issue by poonga** [kartik-v/yii2-widget-datetimepicker#113]
Hi,

I'm Installing the Kartik date picker and DateTime picker with the composer command.

```
composer require kartik-v/yii2-widget-datetimepicker "*"
composer require kartik-v/yii2-widget-datepicker "*"
```

I faced the  Calling unknown method: kartik\datetime\DateTimePicker::isBs() error. 

![image](https://user-images.githubusercontent.com/32412021/145823645-6b4c0c84-571d-402e-9f24-47411538915c.png)

My composer version is 1.

**Comment by Henning-IG** [comment]
I'm having trouble with this, too.
I think there is an issue with dependecies. isBs() is new in yii2-krajee-base 3.0.0. But latest yii2-widget-datetimepicker just requires "kartik-v/yii2-krajee-base": ">=2.0.0" in composer.json
Previous version works for me: "kartik-v/yii2-widget-datetimepicker": "1.4.9",

**Comment by kartik-v** [comment]
Get updated release v1.5.1.
