### ISSUE TITLE
How use yii2-widget-datetimepicker for TYPE_TIMESTAMP?

### ISSUE THREAD

**Issue by gunmetal313** [kartik-v/yii2-widget-datetimepicker#13]
My migrate:

$this->createTable('{{%event}}', [
            'id' => Schema::TYPE_PK,
            'adress' => Schema::TYPE_TEXT . ' NOT NULL',
            'description' => Schema::TYPE_TEXT . ' NOT NULL',
            'header' => Schema::TYPE_TEXT . ' NOT NULL',
            'eventtext' => Schema::TYPE_TEXT . ' NOT NULL',
            'NumberTickets' => Schema::TYPE_INTEGER . ' NOT NULL',
            'Enabled' => Schema::TYPE_BOOLEAN . ' NOT NULL',
            'created_at' => Schema::TYPE_TIMESTAMP . ' NOT NULL',
            'updated_at' => Schema::TYPE_TIMESTAMP . ' NOT NULL',
            'eventtimedateType' => Schema::TYPE_SMALLINT . ' NOT NULL',
            'datetimeevent' => Schema::TYPE_TIMESTAMP . ' NOT NULL'
        ], $tableOptions);

How use yii2-widget-datetimepicker for datetimeevent(TYPE_TIMESTAMP)?

**Comment by kartik-v** [comment]
You need to set the format accordingly -- the format `php:U` will save as Unix timestamp.
