### ISSUE TITLE
Date Range not showing calendar on click of input box.

### ISSUE THREAD

**Issue by mohdbashir** [kartik-v/yii2-widget-datetimepicker#22]
I am using the below code example for date range. It show the form view as shown in image and did not display the calendar on click on input box.

use kartik\date\DatePicker;

echo '<label class="control-label">Select date range</label>';
echo DatePicker::widget([
    'model' => $model,
    'attribute' => 'start_date',
    'attribute2' => 'end_date',
    'options' => ['placeholder' => 'Start date'],
    'options2' => ['placeholder' => 'End date'],
    'type' => DatePicker::TYPE_RANGE,
    'form' => $form,
    'pluginOptions' => [
        'format' => 'dd-M-yyyy',
        'autoclose' => true,
    ]
]);
![date-range](https://cloud.githubusercontent.com/assets/3686692/7793182/c6230b44-02d8-11e5-89cf-1e747181dfcc.png)

**Comment by kartik-v** [comment]
It seems to be not rendering the bootstrap datepicker at all (RATHER the JUI datepicker)... you may need to check if you have JUI enabled or conflicting.

**Comment by mohdbashir** [comment]
But i m using "use kartik\date\DatePicker;"  instead of "use yii\jui\DatePicker;" But in source code it include js file from <script src="/assets/13edcaf/js/bootstrap-datepicker.js?v=1432297614"></script>
