### ISSUE TITLE
Unexpected input format shown.

### ISSUE THREAD

**Issue by marcovtwout** [kartik-v/yii2-widget-datetimepicker#25]
I have a model with a mysql datetime field 'publishFrom'.

My form code is:
`<?= $form->field($model, 'publishFrom')->widget(DateTimePicker::classname()); ?>`

My model rule is:
`   [['publishFrom'], 'date', 'format' => 'yyyy-MM-dd HH:mm'],`

When I load an existing model into the form, the input field shows "2014-11-01 22:00:00". I would like it to show "2014-11-01 22:00", the same format the picker uses by default. Does this extension provide a way to do this?

**Comment by kartik-v** [comment]
You need to convert the model attribute format before you pass to the widget to the same format you want to display.

If you want an automated way to do this...you can use the [DateControl widget](http://demos.krajee.com/datecontrol).
