### ISSUE TITLE
Addon not working with PJAX

### ISSUE THREAD

**Issue by sergeantjonas** [kartik-v/yii2-widget-datetimepicker#27]
Hey,

If you load the addon in a PJAX call all functionalities are lost because the javascript is not being properly registered on the page. Is there any way around this? I think this may be the case for other widgets as well and the cause might be because document.ready is being used instead of a pjax event?

**Comment by kartik-v** [comment]
Refer enh #50. You may set `pjaxContainerId` property in the widget to point to your pjax container identifier and the plugin will be automatically reinitialized on pjax refresh.

**Comment by iddqdidkfa** [comment]
@kartik-v  not working if widget was not present on page before Pjax loads new page content.

**Comment by dmitriy-luch** [comment]
@iddqdidkfa I have the same issue. Did you find any workaround?
@kartik-v do you have any suggestions?

**Comment by kartik-v** [comment]
New enhancements to plugin initialization have been incorporated in kartik-v/yii2-krajee-base#62 that may help achieve other dynamic rendering use cases. You may still need to design and write your client JS accordingly.

**Comment by iddqdidkfa** [comment]
@dmitriy-luch I did not find any workaround, just do not use Pjax containers with `datetimepicker`.
@kartik-v I can't figure out how to write my own client JS to initialize `datetimepicker` that was not present on page initially, but appears on Pjax container reload.
You wrote that widgets now use the `document.body` on `load` event. That's the point. on document body load there is no `datetimepicker` on page.

**Comment by dmitriy-luch** [comment]
@iddqdidkfa I'm rendering hidden datapicker in case there is no on page load. And then on pjax, when I need real DataPicker I render the real one instead of hidden. Then @kartik-v code regarding pjax reload starts to work correctly. This solution is very stupid but it works for now.
Please update here in case you find a solution.
