### ISSUE TITLE
On updating a record with date 0000-00-00 00:00:00 it show November 0

### ISSUE THREAD

**Issue by SOHELAHMED7** [kartik-v/yii2-widget-datetimepicker#28]
Hello Kartik,

I am using Yii 2.0.4 in a project and in that i am using Yii2 datetimepicker widget v1.0.0.
In a record of a table datetime stored is 0000-00-00 00:00:00, and when I update that record it show November 0 or any month name then '0' on the top.
Please see attached image.

Thanks.
Regards,
Sohel Ahmed Mesaniya
sam.wankaner@gmail.com

![update event](https://cloud.githubusercontent.com/assets/6770119/8329203/1d41c57c-1a95-11e5-9092-d71dfcfa6f00.png)

**Comment by kartik-v** [comment]
Not sure why you have a date field with value `0000`. You should ideally set it to null...

But on your question you need to check with the plugin author for [bootstrap-datepicker](https://github.com/eternicode/bootstrap-datepicker).
