### ISSUE TITLE
On updating a record with date 0000-00-00 00:00:00 it show November 0

### ISSUE THREAD

**Issue by SOHELAHMED7** [kartik-v/yii2-widget-datetimepicker#29]
Hello Kartik,

I am using Yii 2.0.4 in a project and in that i am using Yii2 datetimepicker widget v1.0.0.
In a record of a table datetime stored is 0000-00-00 00:00:00, and when I update that record it show November 0 or any month name then '0' on the top.
Please see attached image.
And same in the case of yii2 widget datepicker.
Thanks.
Regards,
Sohel Ahmed Mesaniya
sam.wankaner@gmail.com

![update event](https://cloud.githubusercontent.com/assets/6770119/8329203/1d41c57c-1a95-11e5-9092-d71dfcfa6f00.png)

**Comment by kartik-v** [comment]
Duplicate to #28.
