### ISSUE TITLE
Inputs are saved hours after

### ISSUE THREAD

**Issue by xiandalisay** [kartik-v/yii2-widget-datetimepicker#31]
After inputing the datetime values, the values saved are one to two hours after. I didnt touch beforeSave() 
![capture](https://cloud.githubusercontent.com/assets/7392803/9087076/053d51ca-3bbb-11e5-8985-bff7ab969b91.JPG)
![capture2](https://cloud.githubusercontent.com/assets/7392803/9087074/0538c09c-3bbb-11e5-827a-11c5cbcab094.JPG)

**Comment by jhebb** [comment]
@xlandalisay this is happening to me too, i'm guessing the timezone is not getting set properly. Were you able to resolve it?

**Comment by jhebb** [comment]
Definitely seems to be defaulting to UTC for me, which is +3hrs.

**Comment by xiandalisay** [comment]
Yes, I solved it but It's a detailview issue.  In this attribute, I have the format parameter set to datetime. When I removed it, it was solved. But, I still wanted it to format into a specific datetime format. Still results to "Y-m-d H:i:s"
[
                'attribute'=>'to_dt',
                'label'=>"To",
                'format' => 'datetime', // should be delated
                'value' => "{$model->to_dt}"
            ],

**Comment by xiandalisay** [comment]
Yes, I solved it but It's a detailview issue.  In this attribute, I have
the format parameter set to datetime. When I removed it, it was solved.
But, I still wanted it to format into a specific datetime format. Still
results to "Y-m-d H:i:s"
[
                'attribute'=>'to_dt',
                'label'=>"To",
                'format' => 'datetime', // should be delated
                'value' => "{$model->to_dt}"
            ],

**Comment by jhebb** [comment]
I'm not using detailview to display my data, it's just an ActiveField input but I'll see if it's related.

**Comment by jhebb** [comment]
Setting formatter['defaultTimeZone'] in the config to my time zone corrected this issue for me.
