### ISSUE TITLE
Allow picker button to be set as false for append/prepend

### ISSUE THREAD

**Issue by andrewblake1** [kartik-v/yii2-widget-datetimepicker#35]
Heading meant to be "Bug - pickerButton => false". I have checked this bug by copying your demo page and it does exist there too.

If you have type 2 or 3 i.e. prepend or append with a pickerButton set to false - just wanting the removeButton, then the calendar is also displayed inline.

Have traced thru and seems to occur because of some awkwardness within the plugin - i.e. it turns to inline if the target element is a div (which it needs to be if there is a picker button I guess so that a click on either input or button shows the calendar).

There also seems to be something going on within the plugin to with it recognising and developing process based on the calendar icon's existence.

The simplest solution I have found so far is to position to absolute for the picker button which hides it behind the input and the calendar then shows at correct coordinate. If calendar icon doesn't exist the problems occur - because of the plugin.

Have tried

```
        if ($this->type == self::TYPE_INPUT || $this->pickerButton === false) {
            $this->registerPlugin('datetimepicker');
        } else {
            $this->registerPlugin('datetimepicker', 'jQuery("#' . $this->_container['id'] . '")');
        }
```

however then the remove button doesn't work - the datetimepickerplugin design appears a little awkward in this regard.

**Comment by andrewblake1** [comment]
Further to last comment. I suspect it may be difficult to easily and tidily fix. As no-one else has raised it then perhaps no-one else is trying to use it with just the removeButton and not the pickerButton. Perhaps you could attach to the input, and then attach event to click of the pickerButton separately.

I no longer need it, as have forked the plugin and merged in a PR from 2013 that adds a clear button in the footer of the calendar via allowClear option. Have also added support for disabledDates, and another couple of fixes. I will create a PR for this on the original plugin when I am sure I haven't created any issues. It seems that development and updates has nearly ceased on the plugin with a lot of outstanding PR's.

**Comment by kartik-v** [comment]
In prepend and append mode - the plugin design inherently needs and uses the picker button.

**Comment by andrewblake1** [comment]
Feel free to close. Looking at my second comment, I found another way to deal with it.

As best I can remember ...

I wanted a way to clear the input but didn't want to show the picker button - i.e. wanted the clear button but not the picker button. I expected setting pickerButton => false to have achieved this and left the clear button appended or prepended. I didn't expect this to make the input inline.

**Comment by buttflattery** [comment]
up
