### ISSUE TITLE
Error picking datetime

### ISSUE THREAD

**Issue by kozerog91** [kartik-v/yii2-widget-datetimepicker#38]
Hi,
First of all, thank you for your widgets!

I faced with one problem while using your widget. I suppose there is no "meridiem" in Ukrainian translation. I'm working on multilang project (English, Russian, Ukrainian), and when Ukrainian lang is using there is the next error appear:
![image](https://cloud.githubusercontent.com/assets/9293253/10118926/8fd673d2-648f-11e5-972d-daf2065d0091.png)

Thank you.

**Comment by kartik-v** [comment]
Resolved via #36.
