### ISSUE TITLE
Release info for 1.4.1 is missing

### ISSUE THREAD

**Issue by DmLapin** [kartik-v/yii2-widget-datetimepicker#39]
Tag release 1.4.1 please. It's unavailable via composer at this moment.

**Comment by nikbas** [comment]
It's still at 1.4.0. Should be updated.

**Comment by kartik-v** [comment]
[Refer release v1.4.1](https://github.com/kartik-v/yii2-widget-datetimepicker/releases/tag/v1.4.1)
