### ISSUE TITLE
Yii2 doesnt see module from /vendor

### ISSUE THREAD

**Issue by mushketer888** [kartik-v/yii2-widget-datetimepicker#41]
i installed this extension via composer and tried such example:
use kartik\datetime\DateTimePicker;

echo '<label>Start Date/Time</label>';
echo DateTimePicker::widget([
    'name' => 'datetime_10',
    'options' => ['placeholder' => 'Select operating time ...'],
    'convertFormat' => true,
    'pluginOptions' => [
        'format' => 'd-M-Y g:i A',
        'startDate' => '01-Mar-2014 12:00 AM',
        'todayHighlight' => true
    ]
]);

in result i have:
 PHP Fatal Error – yii\base\ErrorException
Class 'kartik\datetime\DateTimePicker' not found

**Comment by mushketer888** [comment]
Ups sorry in executed composer not from yii/ but from webroot
silly me

**Comment by sohil63** [comment]
@mushketer888 Hello, I am getting the same problem on my live website(which is on shared hosting on godaddy). Can you please tell how you solved it?
