### ISSUE TITLE
DateTimePicker don't work in spanish with Meridiem

### ISSUE THREAD

**Issue by rvences** [kartik-v/yii2-widget-datetimepicker#44]
DateTimePicker don't work in spanish with Meridiem, because it do not exist in locales, please add this code to the spanish locale
yii2-widget-datetimepicker/assets/js/locales/bootstrap-datetimepicker.es.js

```
    meridiem: ["am", "pm"],
    weekStart: 1,
    format: "dd/mm/yyyy hh:ii"
```

**Comment by kartik-v** [comment]
submit a pr
