### ISSUE TITLE
yii2 calender do not appear

### ISSUE THREAD

**Issue by fabiosantos87** [kartik-v/yii2-widget-datetimepicker#53]
I install via composer this plugin and i add in my code the follow example:

use kartik\datetime\DateTimePicker;

echo '<label>Start Date/Time</label>';
echo DateTimePicker::widget([
    'name' => 'datetime_10',
    'options' => ['placeholder' => 'Select operating time ...'],
    'convertFormat' => true,
    'pluginOptions' => [
        'format' => 'd-M-Y g:i A',
        'startDate' => '01-Mar-2014 12:00 AM',
        'todayHighlight' => true
    ]
]);

But when i click in the button to open calender he do not appear. i'm using this scripts:
      
        <script src="/vsoftservice/web/phpGrid/js/i18n/grid.locale-pt.js" type="text/javascript"></script>
        <script src="/vsoftservice/web/phpGrid/js/jquery.jqGrid.min.js" type="text/javascript"></script>

```
    <!-- jQuery UI 1.10.3 -->
    <script src="/vsoftservice/web/js/jquery-ui-1.10.3.min.js" type="text/javascript"></script>

    <!-- Bootstrap -->
  <!--<script src="/js/jquery-1.12.0.min.js" type="text/javascript"></script>-->
    <script src="/vsoftservice/web/js/moment.js" type="text/javascript"></script>
    <script src="/vsoftservice/web/js/moment-with-locales.js" type="text/javascript"></script>
    <script src="/vsoftservice/web/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/vsoftservice/web/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
    <!-- iCheck -->
```

```
    <!-- AdminLTE App -->
    <script src="/vsoftservice/web/js/AdminLTE/app.js" type="text/javascript"></script>
    <script src="/vsoftservice/web/js/jquery-ui-dateTimePiker-Pt.js" type="text/javascript"></script>
```

I can't use jquery version heither because the phpgrid doesn't work. Exists more dependecies.

**Comment by anrus** [comment]
Same issue.

**Comment by anrus** [comment]
In my case it was z-index problem. This helped
`
.datetimepicker{
    z-index: 1000012 !important;
}
`
