### ISSUE TITLE
[FR] Change jquery syntax for events

### ISSUE THREAD

**Issue by fabioaccetta** [kartik-v/yii2-widget-datetimepicker#57]
I'm using your plugin in a common scenario:
```php
[...]
$js = '
function (event) {
	if (event.date)
	{
		[...]
	}
}
';
$pickerOptions['pluginEvents']['changeDate'] = $js;
echo $form->field($model, "attribute_date")
	->widget(DateTimePicker::className(), $pickerOptions);
[...]
```
Looking at the code I see this javascript:
```js
$("#model-attribute_date-datetime").on("changeDate", function (event) {
		if (event.date)
		{
			[...]
		}
	});
```
Is it possible to change the syntax to this?

```js
$(document).on("changeDate", "#model-attribute_date-datetime", function (event) {
		if (event.date)
		{
			[...]
		}
	});
```
It is very useful when the field is deleted via javascript and created again: current javascript does not fire the `changeData` event after appending the new field instance to DOM, while the new syntax does.
Thanks.

**Comment by kartik-v** [comment]
This can be considered as an enhancement in yii2-krajee-base... will update.

**Comment by kartik-v** [comment]
Refer kartik-v/yii2-krajee-base#61.

Will update here with other changes.

**Comment by kartik-v** [comment]
Closed via kartik-v/yii2-krajee-base#61.

**Comment by fabioaccetta** [comment]
Thanks for your changes, but after update I have this javascript:

```js
$(document).on('changeDate', 'jQuery("#model-attribute_date-datetime")', function (event) {
		if (event.date)
		{
			[...]
		}
	});
```
instead of this:
```js
$(document).on('changeDate', '#model-attribute_date-datetime', function (event) {
		if (event.date)
		{
			[...]
		}
	});
```

Looking inside your code, I see that this happens because the function `getPluginScript($name, $element = null, $callback = null, $callbackCon = null)` is called with `$element` already set to `'jQuery("#model-attribute_date-datetime")'`.

**Comment by kartik-v** [comment]
Fixed via update to kartik-v/yii2-krajee-base#61.

**Comment by kartik-v** [comment]
Also refer kartik-v/yii2-krajee-base#62 for an enhancement that better complements this.

**Comment by kartik-v** [comment]
This has to be reverted because of kartik-v/yii2-krajee-base#64.
