### ISSUE TITLE
DateTimePicker don't work

### ISSUE THREAD

**Issue by loveorigami** [kartik-v/yii2-widget-datetimepicker#59]
After 

``` php
        echo '<label>Start Date/Time</label>';
        echo DateTimePicker::widget([
            'name' => 'datetime_10',
            'options' => ['placeholder' => 'Select operating time ...'],
            'convertFormat' => true,
            'pluginOptions' => [
                'format' => 'd-M-Y g:i A',
                'startDate' => '01-Mar-2014 12:00 AM',
                'todayHighlight' => true
            ]
        ]);
```

I have mistake in console

![screenshot 2016-08-10 001](https://cloud.githubusercontent.com/assets/98164/17545697/f2f62992-5ee6-11e6-85e3-7f2f0abc60f6.png)

And DateTimePicker don't work.
Also not work in demo page
http://demos.krajee.com/widget-details/datetimepicker

**Comment by loveorigami** [comment]
You can read about this problem here
https://github.com/smalot/bootstrap-datetimepicker/issues/534

**Comment by AuspeXeu** [comment]
This is fixed in the latest version
