### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by menymen7777** [kartik-v/yii2-widget-datetimepicker#70]
In version 1.4.3 widget don't work. Javascript error in yii2-widget-datetimepicker/assets/js/bootstrap-datetimepicker.js:57. How it fix?

**Comment by hdewaart** [comment]
In version 1.4.3
I get the error
VM582:454 Uncaught TypeError: Cannot read property 'getTime' of undefined.
in version 1.4.2 it's ok

the error is in bootstrap-datetimepicker.js line 454
 return new Date(d.getTime() + (d.getTimezoneOffset() * 60000));
