### ISSUE TITLE
how to disabled minutes selection?

### ISSUE THREAD

**Issue by hbxjw119** [kartik-v/yii2-widget-datetimepicker#77]
Hi, is there any way how to disable minute selection? I need select only full hours.
I have used this widget in a form , and set the options as below:
`'options'=>[
'type'=>DatetimePicker::TYPE_INPUT,
'pluginOptions'=>[
'autoclose'=>true,
'minutesDisabled'=>true]
]
],`
but it didn't work , I have to still choose the minutes
how to solve this?
thanks

**Comment by mailtomotog** [comment]
Try this . it may work
In PluginOptions use 'minView' => 1. it will disable minutes selection.

'pluginOptions'=>['minView' => 1]
