### ISSUE TITLE
No time display when not english

### ISSUE THREAD

**Issue by Commifreak** [kartik-v/yii2-widget-datetimepicker#79]
When I use english as locale, the Widget uses correct time format (Is use Date**Time**Picker, so this should be clear.

en-US
![1](https://cloud.githubusercontent.com/assets/87267/25336778/66736e66-28f9-11e7-968b-cccd2544b660.jpg)

de-DE
![2](https://cloud.githubusercontent.com/assets/87267/25336785/6bd66ce6-28f9-11e7-9cef-39fc2d4d64dc.jpg)

Why is the time here missing? Is something unconfigured here?

Field-Config:

```php
	[
		'attribute' => 'show_till',
		'type' => DetailView::INPUT_DATETIME,
		'widgetOptions' => [
			'pluginOptions' => [
				'autoclose' => true
			]
		]
	],
```

**Comment by Commifreak** [comment]
No idea? Is something wrong with some Yii2 configuration parameters? Id ont got it fixed, yet.

**Comment by kartik-v** [comment]
You have to set the `language` property of the widget to `de`.

**Comment by Commifreak** [comment]
Hi,

I got it - the language is set properly to de, but in the .de locale file, the date format is wrong: https://github.com/kartik-v/yii2-widget-datetimepicker/blob/master/assets/js/locales/bootstrap-datetimepicker.de.js#L16

This would be the file for a datepicker - not for dateTIMEpicker.

Is this fixable through you or should I set this manually? I believe this is a wrong setting for this file.

**Comment by kartik-v** [comment]
No just set the `pluginOptions['format']` property to what you need.

**Comment by kartik-v** [comment]
For example

```
'pluginOptions' => [
    'format' => 'dd.mm.yyyy hh:ii'
]
```

But you can submit a PR to change the `DE` locale file to include a default like above.

**Comment by Commifreak** [comment]
But this is hard coded then. This results in fixed format for every language then, right? It should auto-switch. In my eyes the file has wrong format. The file, linked above, should have defaults to:

`format: 'dd.mm.yyyy HH:ii:ss'` as it's aslo the default for en:

`    getDefaultFormat: function (type, field) {
      if (type == 'standard') {
        if (field == 'input')
          return 'yyyy-mm-dd hh:ii';`


I see, the language files have different defaults - some with time, some without. but it is a dateTIMEpicker, so here we should set the time within defaults. If someone wants no time, we should use the https://github.com/kartik-v/yii2-widget-datepicker or am I wrong?

**Comment by kartik-v** [comment]
As I mentioned you can submit a pull request to change the default format for german language in the `de` locale file... these are defaults from the source plugin (maintained by different author).

**Comment by Commifreak** [comment]
Ok, thanks :)

**Comment by Commifreak** [comment]
Ah, now I understand the "why": The original author did not seperated datepicker and datetimepicker and thus your datetimepicker uses the default locale from the developer.

I create a Pull request ;)
