### ISSUE TITLE
Bugs with date, time and second time date select

### ISSUE THREAD

**Issue by djmaxruby** [kartik-v/yii2-widget-datetimepicker#87]
I just put widget on my page and what do I see?

Ok, instead thousand of words:
![kartik-1](https://user-images.githubusercontent.com/23105443/29771405-3bb4df5a-8bfc-11e7-89e9-0ef9a6063352.png)

And after this when I want to select the date again - i see:
![kartik-2](https://user-images.githubusercontent.com/23105443/29771410-3f6fe612-8bfc-11e7-9500-abdd09a9a859.png)

(facepalm)

**Comment by gomonkey** [comment]
I have the same problem.
this is my code
`'format' => 'y-m-d h:i',`

the y is get a full numeric representation of a year, 4 digits like Y
and m get minutes,

so for example the result can be: 2017-45-8 9:45 

did you find a solution?

**Comment by djmaxruby** [comment]
Good! Thank you for the solution, but I already have changed the widget )

**Comment by ihboy** [comment]
It is ok.
My code: 'format' => 'yyyy-MM-dd HH:mm',
