### ISSUE TITLE
The message file for category 'app' does not exist

### ISSUE THREAD

**Issue by Scentyoo** [kartik-v/yii2-widget-datetimepicker#9]
By using the DateControl-DateTimePicker-Widget I get the following error in my log:
```
The message file for category 'app' does not exist: ********\yii2-website\frontend/messages/de-DE/app.php Fallback file does not exist as well: ********\yii2-website\frontend/messages/de/app.php
```

Here is my code:
```
<?= $form->field($model, 'stop')->widget(DateControl::classname(), [
    'type'=>DateControl::FORMAT_DATETIME,
    'saveFormat' => 'php:U',
    'options' => [
        'pluginOptions' => [
            'todayHighlight' => true,
            'initialDate' => date('d.m.Y').' 23:55',
        ],
        'options' => ['style'=>'width:140px'],
    ],
]) ?>
```

**Comment by kartik-v** [comment]
You normally need to define your `app` level translation messages. Anyway an enhancement has been provided for this widget to have its own i18n translation settings.

**Comment by Scentyoo** [comment]
I updated everything but I still get the same error but now with "kvdatetime":
```The message file for category 'kvdatetime' does not exist```
Where do I need to configure what?

**Comment by Scentyoo** [comment]
Not exactly the same error. Now it points to vendor folder:
```
The message file for category 'kvdatetime' does not exist: ********\vendor\kartik-v\yii2-widget-datetimepicker/messages/de-DE/kvdatetime.php Fallback file does not exist as well: ********\vendor\kartik-v\yii2-widget-datetimepicker/messages/de/kvdatetime.php
```

**Comment by kartik-v** [comment]
As I said, this is related to translations that you must submit for your language. Check messages folder in this widget. You can submit a Pull request for your language file and I will merge it. 

BTW... I have set a default language file for German (de) in the latest update.

**Comment by Scentyoo** [comment]
Perfect, German is what I need! Thank you very much for your fast support and your tools!!

Just because I'm curious: If I would like to use e.g. French, and don't want to send a pull request. Is it possible to configure this clientside?

**Comment by kartik-v** [comment]
Normally you should not override an extension's folder. Its better to send a Pull Request - so that its included with extension and its updates. Once a language translation message file is included, its available for all who need that language.

**Comment by SelenIT** [comment]
I get the error message similar to the one from last @Scentyoo's comment:
> The message file for category 'kvdatetime' does not exist: D:\...\basic\vendor\kartik-v\yii2-widgets/messages/en-US/kvdatetime.php Fallback file does not exist as well: D:\...\basic\vendor\kartik-v\yii2-widgets/messages/en/kvdatetime.php
> D:\...\basic\vendor\kartik-v\yii2-widget-datetimepicker\DateTimePicker.php (152)
> D:\...\basic\vendor\kartik-v\yii2-widget-datetimepicker\DateTimePicker.php (188)
> D:\...\basic\vendor\kartik-v\yii2-widget-datetimepicker\DateTimePicker.php (130)

What looks strange to me that the framework seems to look for message files not in the specific widget folder (`yii2-widget-datetimepicker`), but in the `yii2-widgets` folder. Have I misconfigured something?

I have `'language' => 'ru'` set for the widget, and it correctly displays in Russian.

**Comment by SelenIT** [comment]
Sorry, I found that I was using version 1.4.0, in version 1.4.1 this has been fixed (`$this->initI18N();` replaced with `$this->initI18N($dir);`). Thanks!
