### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTime' of undefined

### ISSUE THREAD

**Issue by hdewaart** [kartik-v/yii2-widget-datetimepicker#95]
When updating from kartik-v/yii2-widget-datetimepicker (v1.4.4 => v1.4.5).
A Uncaught TypeError: Cannot read property 'getTime' of undefined is thrown.

Error seems to be on line 467 of "bootstrap-datetimepicker.js"
"return new Date(d.**_getTime()_** + (d.getTimezoneOffset() * 60000));"

A rollback to version 1.4.4 solves the problem. using yii2-widget-datetimepicker without other plugins.

**Comment by kartik-v** [comment]
Please share what you are doing and configuring in your app to reproduce the issue.

**Comment by hdewaart** [comment]
The error is when opening a bootstrap modal with the FieldRange widget on it.
Without the modal form it's working fine.

use kartik\widgets\ActiveForm;
use kartik\field\FieldRange;
use kartik\tabs\TabsX;
use kartik\datecontrol\DateControl;
use kartik\widgets\Select2;
use kartik\widgets\DepDrop;

(striped widget)
 ```
   <?= FieldRange::widget([
        'form' => $form,
        'model' => $model,
        'attribute1' => 'booked_start',
        'attribute2' => 'booked_end',
        'type' => FieldRange::INPUT_DATETIME,
    ]); ?>
```
if I change INPUT_DATETIME to INPUT_DATE or INPUT_TIME, it's ok.

**Comment by kartik-v** [comment]
Ok - so the issue is to be reported in the `FieldRange` widget and not this widget. Will check.

**Comment by kartik-v** [comment]
Ok cannot reproduce your error. The code works fine on the [demos page with the latest build](http://demos.krajee.com/widget-details/datetimepicker#usage). Can you cross check your app code and if you have the right assets being loaded on your page - or is there something different on your page?

**Comment by hdewaart** [comment]
True.

But did you test it on a modal form?


Kind regards

Hans.

________________________________

**Comment by kartik-v** [comment]
Yes there is a bootstrap modal example in advanced usage as well. Please check.

**Comment by hdewaart** [comment]
Ok I managed to narrowed it down to some kind of solution.
It seems if the input format is "H:i d-m-Y" the error is there.
But if the input format is "d-m-Y H:i" the error is gone.

```
$model->booked_end = date("H:i d-m-Y", strtotime("now"));

<?= FieldRange::widget([
        'form' => $form,
        'model' => $model,
        'label' => 'Start/End',
        'attribute1' => 'booked_start',
        'attribute2' => 'booked_end',
        'type' => FieldRange::INPUT_DATETIME,
    ]);
?>

```

**Comment by kartik-v** [comment]
You need to set the `DateTimePicker::pluginOptions['format']` for your case. Check the 2nd example in the [advanced usage demo](http://demos.krajee.com/widget-details/datetimepicker#advanced-usage).

```php
echo DateTimePicker::widget([
	'name' => 'datetime_11',
	'options' => ['placeholder' => 'Enter event time ...'],
	'convertFormat' => true,
	'pluginOptions' => [
		'todayHighlight' => true,
		'todayBtn' => true,
		'format' => 'php:d-M-Y g:i A',
		'autoclose' => true,
	]
]);
```
