### ISSUE TITLE
strage layout and field auto delete

### ISSUE THREAD

**Issue by funnydj** [kartik-v/yii2-widget-datetimepicker#98]
I'm trying to use a datetime widget whitin a form. So using the advanced demo as example i used this code
```
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\DateTimePicker;

$form = ActiveForm::begin([
                'method' => 'post',
                'action' => Url::to(['/cadute/controller/create']),
]);
echo $form->field($model, 'DATA_CADUTA')->widget(DateTimePicker::classname(), [
                    'options' => ['placeholder' => 'Inserire una data ...'],
                    'pluginOptions' => [
                        'autoclose' => true,
//                        'format' => 'dd/mm/yyyy hh:ii'
                    ]
                ]);

```
When using this widget it has a different layout (more compact) from Datetime and from the one taken in the demo page. (screen https://photoland.io/i/qAIwb)
Also when clicking on the date afeter insertion it's get deleted instantly from the field without the possibility to edit it.

I also tryied to update all dependencies with composer.
php.exe [...]\composer.phar update kartik-v/*
php.exe [...]\composer.phar update kartik-v/yii2-widget-datetimepicke --with-all-dependencies
## Environment
Apache 2.4.23
PHP 7.0.15
yii2 last version 2.0.15.1
#### Browsers
- Mozilla Firefox
#### Operating System
- Windows Server 2012 r2
#### Libraries
- jQuery version: v2.2.4
- yii2-widget-datetimepicker version: 1.4.7 / 1.4.5
## Isolating the problem
- This bug happens when using yii2-widget-datetimepicker without other plugins.

**Comment by buttflattery** [comment]
do you have Jquery Ui also included? or multiple bootstrap css versions?

**Comment by funnydj** [comment]
Only the single and default bootstrap css version is installed (with the official plugin yiisoft/yii-bootstrap version 2.0.8). the strange things is that the DatePicker shows correctly, the DateTimePicker not (just replacing the widget in the same form). Jquery Ui is not installed as far as i know. Is that needed?
Also tryied to update bootstraps
php.exe [...]\composer.phar update yiisoft/yii-boostrap
php.exe [...]\composer.phar update bower-asset/bootstrap
Thanks for response.
