### ISSUE TITLE
RegisterBundle() error

### ISSUE THREAD

**Issue by thomsol** [kartik-v/yii2-widget-datetimepicker#99]
When I try to use the DateTimePicker, I receive the following error:
Call to undefined method kartik\datetime\DateTimePickerAsset::registerBundle()

Since this is inherited, should this just be register()?

I'm a relative newbie, so this may be a dumb question.

Thanks

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-widget-datetimepicker.
- [ ] This is not an usage question. I confirm having gone through and read the documentation for [datetimepicker](http://demos.krajee.com/widget-details/datetimepicker) and [ActiveField](http://demos.krajee.com/widget-details/active-field).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

#### Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-widget-datetimepicker version:

## Isolating the problem

- [ ] This bug happens [on the demos page](http://demos.krajee.com/widget-details/datetimepicker)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-widget-datetimepicker without other plugins.

**Comment by kartik-v** [comment]
You seem to be having outdated package versions of the dependencies to this extension (e.g. yii2-krajee-base). Run a `composer update` on your app environment to get the latest versions of all extensions with their dependencies.

**Comment by thomsol** [comment]
Perfect!!  That did it!  Thank You!!
